// src/executors/mockPatch.ts
//
// Shared by the mocked AI executors (ollama/free_tier/gpt). A real provider
// integration would parse the model's actual response into edits (see
// claude.ts for how the real path does this); these mocks just need a
// deterministic stand-in so the patch-application/checkpoint/rollback path
// can be exercised by AI-tier nodes in the demo/tests, not only by the
// terminal executor.
//
// Convention: packet.context.targetFile (string) or targetFiles (string[])
// requests a file write. Packets that don't set either produce no patch —
// preserves the existing text-only behavior for nodes with nothing to write.

import type { ExecutorName, Patch, TaskPacket } from "../types.js";

export function mockPatchFor(packet: TaskPacket, provider: ExecutorName): Patch | undefined {
  const targets = collectTargets(packet);
  if (targets.length === 0) return undefined;

  return {
    edits: targets.map((path) => ({
      path,
      op: "write" as const,
      content: `// generated by ${provider} (mock)\n// intent: ${packet.intent}\n`,
    })),
  };
}

function collectTargets(packet: TaskPacket): string[] {
  const single = packet.context.targetFile;
  const many = packet.context.targetFiles;
  const targets: string[] = [];
  if (typeof single === "string") targets.push(single);
  if (Array.isArray(many)) targets.push(...many.filter((t): t is string => typeof t === "string"));
  return targets;
}
